apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  labels:
    app: nginx-test
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx-test